### PR TITLE
fix: text overlapping issues on mobile browsers

### LINKED ISSUE #3745: [ENG-10] Text is overlapping
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Text publications with a larger amount of text on Lenster are overlapping on mobile browsers. I've tested Safari, Brave, and Zerion's built-in browsers, but none of them display the textual data without overlapping.

IMG_6206
IMG_6207

### Expected Behavior

Text lines should be displayed one below the other, without being grouped or overlapping.

### Steps To Reproduce

Open Lenster on any of the mentioned mobile browsers, and you should encounter the issue. While I haven't tested it on Chrome or other mobile browsers, I would assume that the behavior is the same.
I'm using an iPhone 13 Pro Max with iOS 16.6.0.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

### Anything else?

**What browser(s) does this occur on?**
 - Every mobile browser I've tried.

I've noticed that there was a previous report for this issue, but it was marked as resolved. However, the issue has returned. Here's the link to the closed report: https://github.com/lensterxyz/lenster/issues/1922"

<sub>[ENG-10](https://linear.app/heyxyz/issue/ENG-10/text-is-overlapping)</sub>

### PR DESCRIPTION
**Pull request by prateekkalra**
## What does this PR do?

This PR fixes the text overlap issue that occurs in text publications in case of long text in iOS mobile browsers.
This issue occurs because of a bug in Safari browser engine when "line-clamp" is used on wrapper elements with multiple blocks.

React markdown generates multiple blocks inside a wrapper, in case of texts seperated by new lines.
For eg. If there are 10 blocks of texts seperated by new line, then the wrapper "div" would container 10 "p" tags.
In this PR, I have limited the wrapper div to have maximum of 1 block in case of ios mobile browsers(all of them uses safari engine- webkit). So, in that case, the users will see only 1 block of code, and see more button. And if 1 block of code is very large, "line-clamp-5" would work flawlessly on the wrapper element. Since there is only 1 block in wrapper div.

This is the best solution possible. There's no CSS workaround, and the JS workaround would get really messy due to the markdown package.
I'm attaching the before and after screenshots below.
hey-safari-before
hey-safari-after

/claim #3745

## Related issues

Fixes #3745

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### <samp>🤖 Generated by Copilot at ee4c76c</samp>

*  Add conditional logic to truncate publication content on iOS mobile devices ([link](https://github.com/heyxyz/hey/pull/3898/files?diff=unified&w=0#diff-6622353deb6c2dcfc2938623f6b6bc3a65857ee5dd42fe6121d16d43eb4f9f73R193-R199), [link](https://github.com/heyxyz/hey/pull/3898/files?diff=unified&w=0#diff-cf87c96f430fb044b052837b8732058bdc59aba03cba72f7f7c43143622ffae1R48-R54))
  - Import `isIOS` and `isMobile` functions from `react-device-detect` library in `DecryptedPublicationBody.tsx` and `PublicationBody.tsx` ([link](https://github.com/heyxyz/hey/pull/3898/files?diff=unified&w=0#diff-6622353deb6c2dcfc2938623f6b6bc3a65857ee5dd42fe6121d16d43eb4f9f73R43), [link](https://github.com/heyxyz/hey/pull/3898/files?diff=unified&w=0#diff-cf87c96f430fb044b052837b8732058bdc59aba03cba72f7f7c43143622ffae1R19))

## Emoji

🐛📱🔒

### CODE REVIEW

File: apps/web/src/components/Publication/DecryptedPublicationBody.tsx [hunk 1]
```diff
@@ -189,6 +190,13 @@ const DecryptedPublicationBody: FC<DecryptedPublicationBodyProps> = ({
     setIsDecrypting(false);
   };
 
+  if (isIOS && isMobile && showMore) {
```
Comment (bigint) [inline apps/web/src/components/Publication/DecryptedPublicationBody.tsx:193]: isIOS will be mobile at the end right?

Comment (bigint) [reply apps/web/src/components/Publication/DecryptedPublicationBody.tsx:193]: I'd suggest to use some other solution instead of hard detecting things, maybe line-clamp in tailwind?

Comment (prateekkalra) [reply apps/web/src/components/Publication/DecryptedPublicationBody.tsx:193]: 1. isIOS will be true for Mac, iPhone and iPad.
2. Tailwind line-clamp seems to work with iphone browsers, but only in case, when wrapper element has a single div.(As mentioned in PR details above) . How can this very specific issue in iphone browser be handled without detecting the user's device?
PS: This issue occurs in all browsers in iPhone & iPad.  (That's why isIOS & isMobile)
https://github.com/duskload/react-device-detect/blob/master/docs/selectors.md

**Comment by bigint** [comment]
Link T-663

**Comment by prateekkalra** [comment]
@bigint Is there anything else that needs to be done, from my end?

**Review by bigint — APPROVED** [review]
